### ISSUE TITLE
nested pie as a subplot 

### ISSUE THREAD

**Issue by lihanyan1990** [NewGuy012/nested_pie#1]
Love this function, however "subplot" doesn't work on this. Every time the function is called, it generated a new figure. Do you think you can make it compatible to subplot?

**Comment by NewGuy012** [comment]
Hello, let me take a look and get back to you.

**Comment by NewGuy012** [comment]
Hi lihanyan1990, so it looks like I had already added in the option to specify a subplot axes using the "AxesHandle" name value pair. Please refer to an example below for reference. I've used "tiledlayout" because it is the recommended method by MathWorks now. But it should still work for "subplot". However, it looks like the default axes background color was set to white. So I've added in a new name value pair "BackgroundColor" in the latest version to allow you to match the color. Also, if you enjoyed this function, it would be much appreciated if you could leave a review in the MathWorks File Exchange page. Thanks!

```
% Initialize data points
inner_pie = [0.1, 0.15, 0.2, 0.05, 0.3, 0.2];
outer_pie = [0.25, 0.25, 0.5];
C = {...
    inner_pie,... % Inner to outer layer
    outer_pie};
outer_label = {...
    '#1',...
    '#2',...
    '#3'};

% Tiled layout
t = tiledlayout(1, 2);

% Spider plot
ax = nexttile;
grey = [0.94, 0.94, 0.94];
nested_pie(C,...
    'PercentStatus', {'off', 'on'},...
    'LabelText', outer_label,...
    'AxesHandle', ax,...
    'BackgroundColor', grey);
ax2 = nexttile;
nested_pie(C,...
    'PercentStatus', {'off', 'on'},...
    'LabelText', outer_label,...
    'AxesHandle', ax2,...
    'BackgroundColor', grey);
```
